# Generated by Django 5.1.3 on 2025-10-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeBeanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CBname', models.CharField(max_length=50)),
                ('CBcoffeeshop', models.CharField(max_length=50)),
                ('CBplace', models.CharField(max_length=50)),
                ('CBroasting', models.CharField(max_length=50)),
                ('CBprice', models.CharField(max_length=50)),
                ('CBflavor', models.CharField(max_length=50)),
                ('CBurl', models.CharField(max_length=200)),
                ('CBcoffeetoday', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Oname', models.CharField(max_length=20)),
                ('Otemperature', models.CharField(max_length=20)),
                ('Ocupnumber', models.IntegerField()),
                ('Oodertime', models.DateTimeField(auto_now_add=True, max_length=50)),
            ],
        ),
    ]
